version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 24
    commands:
      - npm install
  build:
    commands:
      - npm run docs:build
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
  discard-paths: no
